import { PrepTopic } from '../../../app/models/prep-topic';
export const prepTopics: PrepTopic[] = [
    { day: 1, html: 'HTML Boilerplate & Semantic Tags', css: 'Box Model', js: 'var vs let vs const', ts: 'Basic Types', angular: 'Angular CLI & Project Structure' },
    { day: 2, html: 'Forms & Input Types', css: 'Flexbox', js: 'Functions & Scope', ts: 'Interfaces', angular: 'Creating Components' },
    { day: 3, html: 'Input Validation', css: 'Pseudo-classes', js: 'DOM Selection', ts: 'Union & Literal Types', angular: 'Interpolation & Binding' },
    { day: 4, html: 'HTML5 APIs', css: 'Display & Visibility', js: 'Array Methods', ts: 'Type Assertion', angular: 'Ngmodule & its Properties' },
    { day: 5, html: 'Lists & Tables', css: 'Grid Layout', js: 'Objects', ts: 'Type Narrowing', angular: 'Types of Angular Modules – Root, Feature, Shared, and Core' },
    { day: 6, html: 'Media Tags', css: 'Positioning', js: 'Higher-order Functions', ts: 'Enums', angular: 'Lifecycle Hooks' },
    { day: 7, html: 'Meta Tags & SEO', css: 'Typography', js: 'Callbacks & Promises', ts: 'Generics', angular: 'Structural Directives' },
    { day: 8, html: 'Form Accessibility', css: 'Units (em, %, rem)', js: 'Event Handling', ts: 'any vs unknown', angular: 'Attribute Directives' },
    { day: 9, html: 'Anchor Tags & Navigation', css: 'Z-index & Stacking', js: 'ES6 Features', ts: 'Utility Types', angular: 'Routing & RouterLink' },
    { day: 10, html: 'Input Patterns', css: 'Margin vs Padding', js: 'this Keyword', ts: 'Function Overloading', angular: 'Route Params & Guards' },
    { day: 11, html: 'Input Types (tel, email)', css: 'CSS Variables', js: 'Loops & Control Flow', ts: 'Optional Chaining', angular: 'Reactive Forms' },
    { day: 12, html: 'Labels & Fieldsets', css: 'Transitions', js: 'Template Literals', ts: 'Interfaces vs Types', angular: 'Template-driven Forms' },
    { day: 13, html: 'Placeholder & Disabled', css: 'Animations', js: 'Closures', ts: 'Discriminated Unions', angular: 'Form Validation' },
    { day: 14, html: 'Details & Summary', css: 'Hover Effects', js: 'Prototypes', ts: 'Intersection Types', angular: 'Custom Validators' },
    { day: 15, html: 'Iframes & Embedding', css: 'Shadows', js: 'Inheritance', ts: 'Mapped Types', angular: 'HttpClient & API Calls' },
    { day: 16, html: 'HTML Collections vs NodeLists', css: 'Combinators', js: 'JSON Handling', ts: 'Record, Pick, Omit', angular: 'Observables & Subscriptions' },
    { day: 17, html: 'Canvas Element', css: 'Media Queries', js: 'Local Storage', ts: 'Tuples', angular: 'Async Pipe' },
    { day: 18, html: 'Progress & Meter', css: 'CSS Specificity', js: 'Error Handling', ts: 'Type Guards', angular: 'Reactive Patterns' },
    { day: 19, html: 'Accessibility Tags', css: 'Responsive Design', js: 'try/catch', ts: 'keyof and typeof', angular: 'Subjects & BehaviorSubject' },
    { day: 20, html: 'Data-* Attributes', css: 'Grid vs Flex', js: 'Spread & Rest', ts: 'never, unknown', angular: 'Component Tree Review' },
    { day: 21, html: 'Web Accessibility Intro', css: 'Tailwind Setup', js: 'Logical Operators', ts: 'Conditional Types', angular: 'Lazy Loading' },
    { day: 22, html: 'ARIA Roles', css: 'Tailwind Components', js: 'filter, map, reduce', ts: 'Type Inference', angular: 'Standalone Components' },
    { day: 23, html: 'Semantic Structure', css: 'Tailwind Forms', js: 'Currying', ts: 'Type Compatibility', angular: 'Environment Variables' },
    { day: 24, html: 'Validations & Constraints', css: 'Tailwind Responsiveness', js: 'Deep Copy vs Shallow', ts: 'readonly & immutability', angular: 'Module Setup' },
    { day: 25, html: 'Browser Events', css: 'Transform & Scale', js: 'setTimeout vs setInterval', ts: 'Decorators', angular: 'Feature Modules' },
    { day: 26, html: 'Keyboard Navigation', css: 'Transitions & Keyframes', js: 'Hoisting', ts: 'extends & implements', angular: 'Shared Modules' },
    { day: 27, html: 'Role Attributes', css: 'Layout Tricks', js: 'Type Conversion', ts: 'in & instanceof', angular: 'Route Guards Deep Dive' },
    { day: 28, html: 'HTML Entities', css: 'Custom Fonts', js: 'Event Bubbling', ts: 'Generic Constraints', angular: 'Resolver and Route Config' },
    { day: 29, html: 'Autocomplete & Autofocus', css: 'Tailwind Grid', js: 'Memoization', ts: 'Utility Types Recap', angular: 'RxJS Deep Dive' },
    { day: 30, html: 'Summary Styling', css: 'Tailwind Typography', js: 'Set & Map', ts: 'Advanced Type Guards', angular: 'Routing Mastery' },
    { day: 31, html: 'Accessibility Deep Dive', css: 'Tailwind Customization', js: 'Debounce & Throttle', ts: 'Module Augmentation', angular: 'Performance Tuning' },
    { day: 32, html: 'SEO Practices', css: 'Tailwind Cards', js: 'Event Delegation', ts: 'Advanced Interfaces', angular: 'OnPush Strategy' },
    { day: 33, html: 'Custom Elements', css: 'Utility Classes', js: 'Object Destructuring', ts: 'TS Config', angular: 'Preloading Strategy' },
    { day: 34, html: 'Form Submissions', css: 'Responsive Buttons', js: 'Spread in Depth', ts: 'Conditional Types', angular: 'Error Boundaries' },
    { day: 35, html: 'Contenteditable', css: 'CSS Grid Areas', js: 'Prototype Chain', ts: 'Advanced Enums', angular: 'Dynamic Component Loading' },
    { day: 36, html: 'Input Events', css: 'Scroll Behavior', js: 'Closures Recap', ts: 'Advanced Types Recap', angular: 'Testing Basics' },
    { day: 37, html: 'Form API', css: 'Sticky Header', js: 'Recursion', ts: 'Function Types', angular: 'Unit Testing' },
    { day: 38, html: 'HTML5 Doctype', css: 'Button Styling', js: 'Event Loop', ts: 'Type Compatibility', angular: 'Jasmine & Karma' },
    { day: 39, html: 'Validation Patterns', css: 'Custom Checkbox', js: 'Callback Hell', ts: 'Utility Types Practice', angular: 'Writing Test Specs' },
    { day: 40, html: 'Web Forms Analysis', css: 'Loading Spinners', js: 'Execution Context', ts: 'Type vs Interface Nuance', angular: 'Test Selectors' },
    { day: 41, html: 'Accessibility Tree', css: 'Tailwind Grids', js: 'JS Questions Review', ts: 'TS Questions Review', angular: 'Angular Questions Review' },
    { day: 42, html: 'HTML Interview Prep', css: 'UI Principles', js: 'JS Interview Coding', ts: 'TS Interview Coding', angular: 'Angular Interview Coding' },
    { day: 43, html: 'Form Best Practices', css: 'UI/UX Patterns', js: 'JS Design Patterns', ts: 'TS Best Practices', angular: 'Angular Anti-patterns' },
    { day: 44, html: 'Semantics Recap', css: 'Tailwind Strategies', js: 'JS Memory Management', ts: 'Advanced Type Utilities', angular: 'DI Recap' },
    { day: 45, html: 'HTML Optimization', css: 'Responsive Grid Review', js: 'JS Optimization Tips', ts: 'TS Performance Tricks', angular: 'Angular Deployment' },
    { day: 46, html: 'HTML Quiz', css: 'CSS Quiz', js: 'JS Quiz', ts: 'TS Quiz', angular: 'Angular Quiz' },
    { day: 47, html: 'Quick Revise & Flashcards',css: 'One-page CSS Recap',js: 'JS Short Notes',ts: 'TS Cheatsheet',angular: 'Angular Quick Notes'},
    { day: 48, html: 'HTML Interview Recap', css: 'CSS Interview Recap', js: 'JS Interview Recap', ts: 'TS Interview Recap', angular: 'Angular Interview Recap' },
    { day: 49, html: 'Accessibility Final Review', css: 'Tailwind Final Review', js: 'JS Debugging Practice', ts: 'TS Type Challenges', angular: 'Routing & Lazy Loading Review' },
    { day: 50, html: 'HTML Best Practices', css: 'Responsive Design Wrap-up', js: 'JS Performance Tips', ts: 'TS Utility Types Deep Dive', angular: 'Angular Performance Tips' },
    { day: 51, html: 'Quick HTML Quiz', css: 'Quick CSS Quiz', js: 'Quick JS Quiz', ts: 'Quick TS Quiz', angular: 'Quick Angular Quiz' },
    { day: 52, html: 'Accessibility Challenge', css: 'CSS Challenge', js: 'DOM Challenge', ts: 'TS Debug Exercise', angular: 'DI Challenge' },
    { day: 53, html: 'HTML Optimization Tips', css: 'CSS Optimization Tips', js: 'Async Debugging', ts: 'TS Mapping Exercises', angular: 'Service Practice' },
    { day: 54, html: 'HTML Interview Sets', css: 'Tailwind Final Touch', js: 'JS Interview Sets', ts: 'TS Interview Sets', angular: 'Angular Interview Sets' },
    { day: 55, html: 'Problem Solving (HTML)', css: 'Responsive UI Review', js: 'Coding Q&A', ts: 'TS Syntax Practice', angular: 'E2E Practice' },
    { day: 56, html: 'HTML Mock Interview', css: 'CSS Mock Interview', js: 'JS Mock Interview', ts: 'TS Mock Interview', angular: 'Angular Mock Interview' },
    { day: 57, html: 'Quick Revise & Flashcards', css: 'One-page CSS Recap', js: 'JS Short Notes', ts: 'TS Cheatsheet', angular: 'Angular Quick Notes' },
    { day: 58, html: 'Accessibility Wrap-up', css: 'Tailwind Final Projects', js: 'Event-Based Problem Solving', ts: 'Type-centric Challenge', angular: 'Routing Recap' },
    { day: 59, html: 'Review Mistakes', css: 'Polish Styling', js: 'Fix JS Interview Gaps', ts: 'TS Debug Strategy', angular: 'Fix Angular Issues' },
    { day: 60, html: 'Final HTML Task', css: 'Final CSS Task', js: 'Final JS Task', ts: 'Final TS Task', angular: 'Final Angular Task' }

];
export const fundamentals = prepTopics.slice(0, 10);     // Days 1–10
export const intermediate = prepTopics.slice(10, 30);    // Days 11–30
export const advanced = prepTopics.slice(30, 50);        // Days 31–50
export const finalPrep = prepTopics.slice(50, 60);       // Days 51–60